# it is collection of ip's
[appserver]
172.31.43.99 ansible_user=ec2-user ansible_ssh_private_key=/home/ec2-user/'N Virginia Key.pem' 

[dbserver]
172.31.39.140 ansible_user=ec2-user ansible_ssh_private_key=/home/ec2-user/'N Virginia Key.pem' 